server:
  port : 8081

spring:
  datasource:
    username: jihu
    password: 1234
    mapper-locations: classpath:/mappers/**/*.xml
    jdbc-url: jdbc:mariadb://localhost:3306/EVERYFUT
    driver: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:/mybatis/mybatis-config.xml
  type-aliases-package: com.project.everyfut.model  # entity가 존재하는 경로작성.